export const DUMMY_BLOG_DATA = {
  categories: [
    {
      id: 1,
      name: "Công nghệ",
      slug: "cong-nghe",
      description: "Tin tức và bài viết về công nghệ mới nhất",
      imageUrl: "https://example.com/images/technology.jpg",
      createdAt: "2023-04-15T08:30:00Z",
      updatedAt: "2024-02-20T10:15:00Z",
      postsCount: 5,
      featured: true,
      order: 1,
    },
    {
      id: 2,
      name: "Kinh doanh",
      slug: "kinh-doanh",
      description: "Chiến lược và tin tức kinh doanh",
      imageUrl: "https://example.com/images/business.jpg",
      createdAt: "2023-05-10T09:45:00Z",
      updatedAt: "2024-01-15T14:20:00Z",
      postsCount: 4,
      featured: true,
      order: 2,
    },
    {
      id: 3,
      name: "Sức khỏe",
      slug: "suc-khoe",
      description: "Mẹo và lời khuyên để sống khỏe mạnh",
      imageUrl: "https://example.com/images/health.jpg",
      createdAt: "2023-06-22T11:20:00Z",
      updatedAt: "2024-03-05T16:30:00Z",
      postsCount: 6,
      featured: false,
      order: 3,
    },
    {
      id: 4,
      name: "Du lịch",
      slug: "du-lich",
      description: "Khám phá những điểm đến tuyệt vời trên thế giới",
      imageUrl: "https://example.com/images/travel.jpg",
      createdAt: "2023-07-18T13:10:00Z",
      updatedAt: "2024-02-28T09:25:00Z",
      postsCount: 3,
      featured: true,
      order: 4,
    },
    {
      id: 5,
      name: "Ẩm thực",
      slug: "am-thuc",
      description: "Công thức nấu ăn và đánh giá nhà hàng",
      imageUrl: "https://example.com/images/food.jpg",
      createdAt: "2023-08-05T15:40:00Z",
      updatedAt: "2024-01-30T11:50:00Z",
      postsCount: 7,
      featured: false,
      order: 5,
    },
  ],

  posts: [
    // Công nghệ
    {
      id: 1,
      categoryId: 1,
      title: "10 Xu hướng công nghệ AI sẽ thay đổi tương lai",
      slug: "10-xu-huong-cong-nghe-ai-thay-doi-tuong-lai",
      excerpt:
        "Khám phá những xu hướng AI mới nhất đang định hình tương lai của công nghệ và cuộc sống hàng ngày.",
      content:
        "Trí tuệ nhân tạo (AI) đang phát triển với tốc độ chóng mặt và ảnh hưởng đến mọi khía cạnh của cuộc sống hàng ngày. Trong bài viết này, chúng tôi sẽ khám phá 10 xu hướng AI quan trọng nhất sẽ có tác động lớn đến tương lai. Từ xe tự lái đến chăm sóc sức khỏe cá nhân hóa, những tiến bộ trong AI đang mở ra những khả năng mới mà trước đây chỉ tồn tại trong khoa học viễn tưởng. Các doanh nghiệp và cá nhân nên chuẩn bị như thế nào cho những thay đổi này? Hãy cùng tìm hiểu...",
      author: {
        id: 1,
        name: "Nguyễn Văn A",
        avatar: "https://example.com/images/authors/nguyen-van-a.jpg",
        bio: "Chuyên gia công nghệ với hơn 10 năm kinh nghiệm trong ngành",
      },
      imageUrl: "https://example.com/images/posts/ai-trends.jpg",
      tags: ["AI", "Machine Learning", "Công nghệ", "Tương lai", "Innovation"],
      publishedAt: "2024-01-15T08:00:00Z",
      createdAt: "2024-01-10T14:30:00Z",
      updatedAt: "2024-01-14T16:45:00Z",
      viewCount: 3450,
      commentCount: 28,
      likeCount: 156,
      featured: true,
      status: "published",
    },
    {
      id: 2,
      categoryId: 1,
      title: "Đánh giá iPhone 16 Pro: Có đáng để nâng cấp?",
      slug: "danh-gia-iphone-16-pro-co-dang-de-nang-cap",
      excerpt:
        "Đánh giá chi tiết về iPhone 16 Pro, những tính năng mới và liệu có đáng để nâng cấp từ mẫu cũ.",
      content:
        "Apple vừa ra mắt iPhone 16 Pro với nhiều cải tiến đáng chú ý về hiệu năng, camera và tuổi thọ pin. Nhưng liệu những cải tiến này có đủ để thuyết phục người dùng nâng cấp từ các mẫu cũ? Trong bài đánh giá này, chúng tôi sẽ phân tích chi tiết về thiết kế, màn hình, hiệu năng, camera và thời lượng pin của iPhone 16 Pro. Chúng tôi cũng so sánh nó với iPhone 15 Pro để giúp bạn đưa ra quyết định mua hàng sáng suốt...",
      author: {
        id: 2,
        name: "Trần Thị B",
        avatar: "https://example.com/images/authors/tran-thi-b.jpg",
        bio: "Reviewer công nghệ với chuyên môn về các sản phẩm Apple",
      },
      imageUrl: "https://example.com/images/posts/iphone-16-pro-review.jpg",
      tags: ["iPhone", "Apple", "Smartphone", "Review", "Tech"],
      publishedAt: "2024-02-22T10:30:00Z",
      createdAt: "2024-02-18T09:15:00Z",
      updatedAt: "2024-02-21T17:40:00Z",
      viewCount: 5680,
      commentCount: 42,
      likeCount: 205,
      featured: true,
      status: "published",
    },
    {
      id: 3,
      categoryId: 1,
      title: "Hướng dẫn xây dựng PC Gaming trong năm 2025",
      slug: "huong-dan-xay-dung-pc-gaming-2025",
      excerpt:
        "Mọi thứ bạn cần biết để xây dựng một PC chơi game mạnh mẽ trong năm 2025.",
      content:
        "Xây dựng PC gaming có thể là một trải nghiệm thú vị nhưng cũng đầy thách thức. Với vô số lựa chọn về CPU, GPU, mainboard và các thành phần khác, việc quyết định cấu hình phù hợp với ngân sách và nhu cầu của bạn có thể gây nhầm lẫn. Hướng dẫn này sẽ giúp bạn điều hướng qua quá trình xây dựng PC gaming từ A đến Z, bao gồm lựa chọn linh kiện, lắp ráp và tối ưu hóa hiệu suất...",
      author: {
        id: 3,
        name: "Lê Văn C",
        avatar: "https://example.com/images/authors/le-van-c.jpg",
        bio: "Chuyên gia phần cứng máy tính và game thủ chuyên nghiệp",
      },
      imageUrl: "https://example.com/images/posts/gaming-pc-build.jpg",
      tags: ["Gaming", "PC Build", "Hardware", "RTX", "AMD"],
      publishedAt: "2024-03-10T12:00:00Z",
      createdAt: "2024-03-05T08:20:00Z",
      updatedAt: "2024-03-09T15:30:00Z",
      viewCount: 4120,
      commentCount: 56,
      likeCount: 183,
      featured: false,
      status: "published",
    },
    {
      id: 4,
      categoryId: 1,
      title: "Hiểu về Blockchain và tiềm năng của nó ngoài tiền điện tử",
      slug: "hieu-ve-blockchain-va-tiem-nang-ngoai-tien-dien-tu",
      excerpt:
        "Khám phá cách công nghệ blockchain đang được áp dụng vượt ra ngoài Bitcoin và tiền điện tử.",
      content:
        "Mặc dù blockchain thường được biết đến nhiều nhất thông qua Bitcoin và các loại tiền điện tử khác, nhưng tiềm năng của công nghệ này vượt xa lĩnh vực tài chính. Từ chuỗi cung ứng đến chăm sóc sức khỏe, blockchain đang cách mạng hóa cách các tổ chức lưu trữ, xác minh và bảo mật dữ liệu. Bài viết này sẽ giải thích cách hoạt động của blockchain, các ứng dụng của nó ngoài tiền điện tử và cách nó có thể định hình tương lai của các ngành công nghiệp khác nhau...",
      author: {
        id: 4,
        name: "Phạm Thị D",
        avatar: "https://example.com/images/authors/pham-thi-d.jpg",
        bio: "Chuyên gia về blockchain và công nghệ tài chính",
      },
      imageUrl: "https://example.com/images/posts/blockchain-applications.jpg",
      tags: ["Blockchain", "Crypto", "Technology", "Innovation", "Fintech"],
      publishedAt: "2024-02-05T09:15:00Z",
      createdAt: "2024-01-29T13:40:00Z",
      updatedAt: "2024-02-04T11:25:00Z",
      viewCount: 2850,
      commentCount: 19,
      likeCount: 97,
      featured: false,
      status: "published",
    },
    {
      id: 5,
      categoryId: 1,
      title: "5 Ngôn ngữ lập trình phổ biến nhất để học trong năm 2025",
      slug: "5-ngon-ngu-lap-trinh-pho-bien-nhat-2025",
      excerpt:
        "Tìm hiểu về những ngôn ngữ lập trình đang được ưa chuộng nhất và tại sao bạn nên học chúng.",
      content:
        "Thế giới lập trình liên tục phát triển, vì vậy việc chọn đúng ngôn ngữ để học là điều cần thiết cho sự phát triển nghề nghiệp của bạn. Dựa trên xu hướng thị trường, nhu cầu của ngành và mức lương, chúng tôi đã xác định 5 ngôn ngữ lập trình hàng đầu đáng để học trong năm 2025. Từ Python đa năng đến Rust tập trung vào hiệu suất, danh sách này cung cấp sự cân bằng giữa các lựa chọn đã được thiết lập và các ngôn ngữ đang nổi lên...",
      author: {
        id: 5,
        name: "Hoàng Văn E",
        avatar: "https://example.com/images/authors/hoang-van-e.jpg",
        bio: "Senior Developer với 15 năm kinh nghiệm trong nhiều ngôn ngữ lập trình",
      },
      imageUrl: "https://example.com/images/posts/programming-languages.jpg",
      tags: ["Programming", "Python", "JavaScript", "Rust", "Career"],
      publishedAt: "2024-01-30T14:45:00Z",
      createdAt: "2024-01-25T10:30:00Z",
      updatedAt: "2024-01-29T16:15:00Z",
      viewCount: 6250,
      commentCount: 37,
      likeCount: 218,
      featured: false,
      status: "published",
    },

    // Kinh doanh
    {
      id: 6,
      categoryId: 2,
      title:
        "Các chiến lược marketing hiệu quả cho doanh nghiệp nhỏ trong năm 2025",
      slug: "chien-luoc-marketing-hieu-qua-doanh-nghiep-nho-2025",
      excerpt:
        "Khám phá các chiến lược marketing chi phí thấp nhưng hiệu quả cao dành cho doanh nghiệp nhỏ.",
      content:
        "Marketing hiệu quả không nhất thiết phải tốn kém. Đặc biệt đối với các doanh nghiệp nhỏ với ngân sách hạn chế, việc tìm ra các chiến lược marketing sáng tạo và tiết kiệm chi phí là rất quan trọng. Bài viết này chia sẻ 10 chiến lược marketing đã được chứng minh mà các doanh nghiệp nhỏ có thể triển khai trong năm 2025 để tăng khả năng hiển thị, thu hút khách hàng tiềm năng và thúc đẩy tăng trưởng. Từ tiếp thị nội dung đến tận dụng mạng xã hội và email marketing, những chiến lược này sẽ giúp doanh nghiệp của bạn cạnh tranh hiệu quả với các đối thủ lớn hơn...",
      author: {
        id: 6,
        name: "Nguyễn Thị F",
        avatar: "https://example.com/images/authors/nguyen-thi-f.jpg",
        bio: "Chuyên gia marketing với hơn 8 năm kinh nghiệm làm việc với doanh nghiệp vừa và nhỏ",
      },
      imageUrl: "https://example.com/images/posts/small-business-marketing.jpg",
      tags: ["Marketing", "SMB", "Digital Marketing", "Strategy", "Growth"],
      publishedAt: "2024-02-12T09:30:00Z",
      createdAt: "2024-02-07T14:20:00Z",
      updatedAt: "2024-02-11T16:45:00Z",
      viewCount: 3780,
      commentCount: 25,
      likeCount: 142,
      featured: true,
      status: "published",
    },
    {
      id: 7,
      categoryId: 2,
      title: "Cách huy động vốn cho startup của bạn: Hướng dẫn toàn diện",
      slug: "cach-huy-dong-von-cho-startup-huong-dan-toan-dien",
      excerpt:
        "Tìm hiểu các phương pháp khác nhau để huy động vốn cho doanh nghiệp khởi nghiệp và cách chọn phương pháp phù hợp nhất.",
      content:
        "Huy động vốn là một trong những thách thức lớn nhất mà các nhà sáng lập startup phải đối mặt. Từ bootstrap đến venture capital, có nhiều cách khác nhau để tài trợ cho doanh nghiệp của bạn, mỗi cách đều có ưu và nhược điểm riêng. Hướng dẫn này sẽ giúp bạn hiểu rõ về các tùy chọn huy động vốn khác nhau, từ giai đoạn hạt giống đến Series A và hơn thế nữa. Chúng tôi cũng sẽ chia sẻ lời khuyên về cách chuẩn bị pitch deck, đàm phán điều khoản và xây dựng mối quan hệ với các nhà đầu tư...",
      author: {
        id: 7,
        name: "Trần Văn G",
        avatar: "https://example.com/images/authors/tran-van-g.jpg",
        bio: "Nhà đầu tư thiên thần và cố vấn khởi nghiệp",
      },
      imageUrl: "https://example.com/images/posts/startup-funding.jpg",
      tags: [
        "Startup",
        "Funding",
        "Venture Capital",
        "Angel Investment",
        "Entrepreneurship",
      ],
      publishedAt: "2024-01-25T11:00:00Z",
      createdAt: "2024-01-20T08:45:00Z",
      updatedAt: "2024-01-24T15:30:00Z",
      viewCount: 4250,
      commentCount: 31,
      likeCount: 176,
      featured: true,
      status: "published",
    },
    {
      id: 8,
      categoryId: 2,
      title: "Xu hướng thương mại điện tử sẽ định hình ngành trong năm 2025",
      slug: "xu-huong-thuong-mai-dien-tu-dinh-hinh-nganh-2025",
      excerpt:
        "Khám phá những xu hướng thương mại điện tử mới nổi và cách chuẩn bị cho doanh nghiệp của bạn.",
      content:
        "Thương mại điện tử tiếp tục phát triển với tốc độ chóng mặt, được thúc đẩy bởi công nghệ mới, thay đổi hành vi người tiêu dùng và sự gián đoạn của ngành. Bài viết này phân tích 7 xu hướng thương mại điện tử quan trọng nhất sẽ định hình ngành vào năm 2025, bao gồm thương mại xã hội, mua sắm dựa trên AR/VR, tính bền vững và thương mại không tiếp xúc. Chúng tôi cũng cung cấp những hiểu biết thực tế về cách các doanh nghiệp thương mại điện tử có thể tận dụng những xu hướng này để thu hút khách hàng, tăng doanh số bán hàng và đi trước đối thủ cạnh tranh...",
      author: {
        id: 8,
        name: "Lê Thị H",
        avatar: "https://example.com/images/authors/le-thi-h.jpg",
        bio: "Chuyên gia thương mại điện tử và chiến lược số",
      },
      imageUrl: "https://example.com/images/posts/ecommerce-trends.jpg",
      tags: [
        "E-commerce",
        "Retail",
        "Shopping",
        "Digital Transformation",
        "Consumer Trends",
      ],
      publishedAt: "2024-03-05T13:15:00Z",
      createdAt: "2024-02-28T10:20:00Z",
      updatedAt: "2024-03-04T16:40:00Z",
      viewCount: 2980,
      commentCount: 22,
      likeCount: 135,
      featured: false,
      status: "published",
    },
    {
      id: 9,
      categoryId: 2,
      title:
        "Cách cải thiện sự hài lòng của khách hàng và tăng tỷ lệ giữ chân khách hàng",
      slug: "cach-cai-thien-su-hai-long-cua-khach-hang",
      excerpt:
        "Chiến lược và mẹo thiết thực để nâng cao trải nghiệm khách hàng và xây dựng lòng trung thành.",
      content:
        "Việc thu hút khách hàng mới rất tốn kém, vì vậy việc giữ chân khách hàng hiện tại là điều cần thiết cho sự phát triển kinh doanh bền vững. Bài viết này khám phá các chiến lược đã được chứng minh để cải thiện sự hài lòng của khách hàng, tạo ra trải nghiệm xuất sắc và xây dựng lòng trung thành lâu dài. Từ cá nhân hóa đến dịch vụ khách hàng chủ động và các chương trình khách hàng thân thiết, chúng tôi chia sẻ các phương pháp hay nhất có thể áp dụng cho doanh nghiệp ở mọi quy mô...",
      author: {
        id: 9,
        name: "Phạm Văn I",
        avatar: "https://example.com/images/authors/pham-van-i.jpg",
        bio: "Chuyên gia về trải nghiệm khách hàng và chiến lược tăng trưởng",
      },
      imageUrl: "https://example.com/images/posts/customer-satisfaction.jpg",
      tags: [
        "Customer Experience",
        "CX",
        "Customer Retention",
        "Loyalty",
        "Business Growth",
      ],
      publishedAt: "2024-03-18T10:45:00Z",
      createdAt: "2024-03-12T09:30:00Z",
      updatedAt: "2024-03-17T14:20:00Z",
      viewCount: 1850,
      commentCount: 13,
      likeCount: 87,
      featured: false,
      status: "published",
    },

    // Sức khỏe
    {
      id: 10,
      categoryId: 3,
      title:
        "Cách xây dựng thói quen ăn uống lành mạnh mà vẫn thưởng thức đồ ăn bạn yêu thích",
      slug: "xay-dung-thoi-quen-an-uong-lanh-manh",
      excerpt:
        "Khám phá cách tiếp cận cân bằng đối với dinh dưỡng giúp bạn ăn uống lành mạnh đồng thời vẫn tận hưởng những món ăn yêu thích.",
      content:
        "Việc ăn uống lành mạnh không có nghĩa là phải từ bỏ những món ăn bạn yêu thích hoặc tuân theo chế độ ăn kiêng hà khắc. Thay vào đó, đó là về việc tìm ra sự cân bằng bền vững và phát triển một mối quan hệ tích cực với thực phẩm. Bài viết này chia sẻ 8 chiến lược thiết thực để tạo ra những thói quen ăn uống lành mạnh và bền vững, bao gồm kế hoạch bữa ăn, chế biến thực phẩm, ăn uống có ý thức và cách kết hợp những món ăn ưa thích một cách có trách nhiệm. Với những lời khuyên này, bạn có thể đạt được mục tiêu dinh dưỡng mà không cảm thấy bị tước đoạt...",
      author: {
        id: 10,
        name: "Nguyễn Văn J",
        avatar: "https://example.com/images/authors/nguyen-van-j.jpg",
        bio: "Chuyên gia dinh dưỡng và huấn luyện viên sức khỏe",
      },
      imageUrl: "https://example.com/images/posts/healthy-eating-habits.jpg",
      tags: ["Nutrition", "Healthy Eating", "Diet", "Wellness", "Food"],
      publishedAt: "2024-01-10T10:30:00Z",
      createdAt: "2024-01-05T14:45:00Z",
      updatedAt: "2024-01-09T16:20:00Z",
      viewCount: 7380,
      commentCount: 48,
      likeCount: 265,
      featured: true,
      status: "published",
    },
    {
      id: 11,
      categoryId: 3,
      title: "Hướng dẫn toàn diện về thiền cho người mới bắt đầu",
      slug: "huong-dan-toan-dien-ve-thien-cho-nguoi-moi",
      excerpt:
        "Tìm hiểu cách bắt đầu thực hành thiền và tích hợp nó vào cuộc sống hàng ngày của bạn.",
      content:
        "Thiền là một công cụ mạnh mẽ để giảm căng thẳng, cải thiện sự tập trung và nâng cao sức khỏe tinh thần tổng thể. Nhưng đối với người mới bắt đầu, thiền có thể dường như khó tiếp cận hoặc bí ẩn. Hướng dẫn thân thiện với người mới bắt đầu này phá vỡ các khái niệm cơ bản của thiền, các lợi ích được hỗ trợ khoa học và các kỹ thuật thiền đơn giản mà bạn có thể bắt đầu ngay hôm nay. Chúng tôi cũng giải quyết các thách thức phổ biến mà người mới thiền gặp phải và cung cấp lời khuyên thiết thực về cách xây dựng một thói quen thiền bền vững...",
      author: {
        id: 11,
        name: "Trần Thị K",
        avatar: "https://example.com/images/authors/tran-thi-k.jpg",
        bio: "Giáo viên thiền và huấn luyện viên chánh niệm được chứng nhận",
      },
      imageUrl: "https://example.com/images/posts/meditation-guide.jpg",
      tags: [
        "Meditation",
        "Mindfulness",
        "Mental Health",
        "Wellness",
        "Stress Relief",
      ],
      publishedAt: "2024-02-15T09:15:00Z",
      createdAt: "2024-02-10T13:40:00Z",
      updatedAt: "2024-02-14T11:30:00Z",
      viewCount: 5620,
      commentCount: 36,
      likeCount: 223,
      featured: false,
      status: "published",
    },
  ],
};
